apiVersion: v1
data:
  bundle.yaml: |
    apiVersion: "1"
    id: "jenkins"
    description: "SMARTTEK BUNDLE"
    version: "1"
    jcasc:
      - "jenkins.yaml"
    plugins:
      - "plugins.yaml"
  jenkins.yaml: |
    jenkins:
      agentProtocols:
      - "Diagnostic-Ping"
      - "JNLP4-connect"
      - "OperationsCenter2"
      - "Ping"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: false
      disableRememberMe: false
      labelAtoms:
      - name: "built-in"
      markupFormatter: "plainText"
      mode: NORMAL
      myViewsTabBar: "standard"
      noUsageStatistics: true
      numExecutors: 2
      primaryView:
        masters:
          columns:
          - "status"
          - "weather"
          - "jobName"
          - "manageMaster"
          - "masterConfigurationStaleViewColumn"
          - "totalJobsViewColumn"
          - "queueSizeViewColumn"
          - "jenkinsVersionViewColumn"
          - "listSelectionColumn"
          jobFilters:
          - "connectedMasterViewFilter"
          name: "Controllers"
          recurse: true
      projectNamingStrategy: "standard"
      quietPeriod: 5
      remotingSecurity:
        enabled: true
      scmCheckoutRetryCount: 0
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "admin"
            properties:
            - "blueSteelRedirectOptOutProperty"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
            - mailer:
                emailAddress: "admin@test.com"
            - "apiToken"
      slaveAgentPort: 50000
      updateCenter:
        sites:
        - id: "core-oc-offline"
          url: "file:/tmp/jenkins/war/WEB-INF/plugins/update-center.json"
        - id: "cap-core-oc"
          url: "https://jenkins-updates.cloudbees.com/update-center/envelope-core-oc/update-center.json"
      views:
      - masters:
          columns:
          - "status"
          - "weather"
          - "jobName"
          - "manageMaster"
          - "masterConfigurationStaleViewColumn"
          - "totalJobsViewColumn"
          - "queueSizeViewColumn"
          - "jenkinsVersionViewColumn"
          - "listSelectionColumn"
          jobFilters:
          - "connectedMasterViewFilter"
          name: "Controllers"
          recurse: true
      - all:
          name: "all"
      viewsTabBar: "standard"
    cloudbees-monitoring:
      recipientList:
      - email:
          emailAddresses: "alerts@test.com"
          subjectPrefix: "[Jenkins Alert]"
    advisor:
      acceptToS: true
      email: "admin@test.com"
      excludedComponents:
      - "AgentsSystemConfiguration"
      - "KubernetesMasterLogs"
      - "AgentsJVMProcessSystemMetricsContents"
      - "GCLogs"
      - "AgentsConfigFile"
      - "ConfigFileComponent"
      - "RootCAs"
      - "SlaveLogs"
      - "OtherConfigFilesComponent"
      - "HeapUsageHistogram"
      - "OtherLogs"
      - "SlaveLaunchLogs"
      nagDisabled: false
    beekeeper:
      enabled: true
      securityWarnings:
        enabledForCore: true
        enabledForPlugins: true
      upgrades:
        autoDowngradePlugins: false
        autoUpgradePlugins: true
    notificationConfiguration:
      enabled: false
    cloudBeesCasCServer:
      disableRemoteValidation: false
      visibility: false
    license:
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIGcjCCBFqgAwIBAgIEAbAOLjANBgkqhkiG9w0BAQUFADBKMQswCQYDVQQGEwJV
        UzERMA8GA1UECAwIRGVsYXdhcmUxDjAMBgNVBAcMBUxld2VzMRgwFgYDVQQKDA9D
        bG91ZEJlZXMsIEluYy4wHhcNMjMwNTAxMDAwMDAwWhcNMjMwOTMwMjM1OTU5WjCC
        Am4xETAPBgorBgEEAYKpfwEBEwEzMTAwLgYKKwYBBAGCqX8BAhMgKjBhNTA2MDkw
        ZDQ1M2MxZTc1YzFhYzQzYTQ5N2U1NCoxFTATBgsrBgEEAYKpfwELDhMEdHJ1ZTEV
        MBMGCysGAQQBgql/AQsNEwR0cnVlMRUwEwYLKwYBBAGCqX8BCxATBHRydWUxFTAT
        BgsrBgEEAYKpfwELDxMEdHJ1ZTEVMBMGCysGAQQBgql/AQsKEwR0cnVlMRUwEwYL
        KwYBBAGCqX8BCwwTBHRydWUxFTATBgsrBgEEAYKpfwELCxMEdHJ1ZTEVMBMGCysG
        AQQBgql/AQsREwR0cnVlMRUwEwYLKwYBBAGCqX8BCwcTBHRydWUxFTATBgsrBgEE
        AYKpfwELBhMEdHJ1ZTEVMBMGCysGAQQBgql/AQsJEwR0cnVlMRUwEwYLKwYBBAGC
        qX8BCwgTBHRydWUxFTATBgsrBgEEAYKpfwELAxMEdHJ1ZTEVMBMGCysGAQQBgql/
        AQsCEwR0cnVlMRUwEwYLKwYBBAGCqX8BCwUTBHRydWUxFTATBgsrBgEEAYKpfwEL
        BBMEdHJ1ZTEVMBMGCysGAQQBgql/AQsBEwR0cnVlMRUwEwYLKwYBBAGCqX8BCxQT
        BHRydWUxFTATBgsrBgEEAYKpfwELFRMEdHJ1ZTETMBEGCisGAQQBgql/AQMTAzEw
        MDESMBAGCisGAQQBgql/AQ4TAjEwMRQwEgYKKwYBBAGCqX8BCRMEdHJ1ZTEQMA4G
        A1UEAxMHc21hcnRlazEJMAcGA1UECxMAMRYwFAYLKwYBBAGCqX8BCxgTBWZhbHNl
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwMCWWDto+4o5wkTz1Xp4
        bXJhFQGArgcEKajKQeqjEPGgSRBt8JMYmyfSXvzN0Ft6evFJWlAJPautR2BQ3WFz
        FVijMHxeZf4zwBmXWI38Sgd33tQ9DCjx2b22pnY4zvMOo6VHWiS2HhAvVHcnljFe
        IBw/w374uywdl41onJvPuJpe1z9sRZYSGJw7DXq1zleuWoGPQogJBdCFK+oPPbIj
        uCjBCZp5fgcFuT8XSDsjpzOOUwtNOgjdBEUYnAvSHyNHtvuWEYRccF3NlSh/D+Pd
        t4zhGsJyijYUaR0Fv9lbdA35i77NQJVpC7/oS7NoVvyYXR4QcNWWymsBkR3haxmf
        qwIDAQABozowODAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBTHoeBMAf/p7u+yppT5
        1ER9PzOwNDAJBgNVHSMEAjAAMA0GCSqGSIb3DQEBBQUAA4ICAQBBQCTydgzSngfa
        q8oUZFDFIrE+SQL1vjOjItfebKjAOvbvziBxmAEaOyKrx+4E6gIrB/+ywIzPryPh
        m/Avj9QeO4216Wvat6dxCsjJgRJIwLoJci/r28xfxNni1a7w1CQcKG8rbMkuyzEc
        3eYhYq/qOTFw8cZHEr8dfamZN42c8i9CQPoqy8y++mB15zjwpqNlOZ5Qrs8G3cD6
        +HKE04M8vJsYOMDx9al/3T4exlMIbdTBMI7Npz5zZ40PDdg62hgW06M0NinGj5kJ
        NBinLRjYOJ7Qk40408UlK78UJJv4Xjcq0NdpiUurK3VALjbr8e9mEF+LvAQeWjlR
        0fuCiQ1IJ0TzXL2v889n+6d0IWrsp/IxhIjMmmpoAU/ixtxMqxj524CsjpYrBns2
        RM8ojfbK4xvxxn6CE/W998nfL6m8bhh9jrSbQZWms3UtwAS0xbF/SlTy7v15a8vI
        7fEcKEISGoFRSuKaMjnYPcrqZe5lBmL8LDs5SFtTQEYcz1HhWwvOuWKX4L+tS3J6
        PYOt918dbJidaSrNhCbAfHAkB1oibCcFW5w3CBuhBhqiAbpJyT1b6QJwyC9pIXMP
        AFLmp6SK1rLxOXL5x1Yf7vI2HulGQQCQQb5Y3pc1w74Mb/ksqn5f1DOeHSQCmPI0
        JDj2vYe17loLDAIWewyhQhhzvmo+MA==
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAwMCWWDto+4o5wkTz1Xp4bXJhFQGArgcEKajKQeqjEPGgSRBt
        8JMYmyfSXvzN0Ft6evFJWlAJPautR2BQ3WFzFVijMHxeZf4zwBmXWI38Sgd33tQ9
        DCjx2b22pnY4zvMOo6VHWiS2HhAvVHcnljFeIBw/w374uywdl41onJvPuJpe1z9s
        RZYSGJw7DXq1zleuWoGPQogJBdCFK+oPPbIjuCjBCZp5fgcFuT8XSDsjpzOOUwtN
        OgjdBEUYnAvSHyNHtvuWEYRccF3NlSh/D+Pdt4zhGsJyijYUaR0Fv9lbdA35i77N
        QJVpC7/oS7NoVvyYXR4QcNWWymsBkR3haxmfqwIDAQABAoIBAGduMH7SCmiH6Kx9
        UZZpLHwWV0/tSX6Y1zv/jeDHJo9uCQOL5GKmnBqNyM4du9clb1jPZvwmXH8SQ148
        qcfRhe6bbJ4U7pauTFi1osfrEMksrr8MhmGjCvw7V+qFH8C1HlLj2qDdeDgzmSIq
        +jwW65oxbmnaFWBisNJlGBCJb3JvvDgdTp44l3WFcoygGbkejo5Qhggv/whNoWX+
        or6D7UJYLpH8hSsuIRC+zDs6QsK/z3Z+4PPVqzBdy1n33dWiOeGgDOdVpp+UpIXs
        2Hb4BHTWMyW0Xyo5AuvkqExPZ+5IAPSW0Gkg5b7X6fOPYlWMg90iyCJ2b3FrdiB7
        a14vMUECgYEA80YX2VV7y7Tm67zx1hL6DBCEriAJyH7fqYZNCNa67Lc9Ji/z5BqK
        iUwRvU1NaHMvZSbLOL4lwfzk9OZyos71709qB2ImA/hEDMNcLshQJxcOGZuBt4l5
        5+eUQ0hl1UBooP3meIjDHkJFdb7to1mIOD0iEBeXv8QGBfEUD1ag3QsCgYEAytXp
        1Kz58uRndFo4EYID8egKdebaAluJC+YFyXTqa0atVDVMs6i/wSzr6m94foGXHJHZ
        OVXJ6S96jUACm9VGqOy9v2d+VQ2oNLwnPzXcwrZJEiRt7EJfnQE/7wDN00eoaKyJ
        jTcO+bO1KJYQ6sV7s/dQ7DJv+ZMlMgwoVmzTq+ECgYAyiQb/QMC8qlGl+tQJ8ls7
        EltdiI4/tgtkPd/WzDR8Y/wx6JgzdEf/CWxN9Lb10aewzYQ9v1I8n/o33X9GztNL
        6SVPb1YSUQph1Ftb5ISx+hoVu7YQmGBYikTETU/KIt0ZRGUR+Ob/bCjdstHOsxSX
        Civ/R8dgMKpHpbLTFN3JzQKBgDfCVmWAp7V91HLH2mH1u9/kSfvfWk8LmsEKmsym
        t0qGQ1/CxzMcUJpqHvBzdExSk5fnADAixT61Lptl3VG5b5NAgWj8ql33QyY8Ew3t
        YKKmObAjE5S/Kkme7lRlhC9wo3si8y0+1X8PR93AYyYm47q1YimMM/wH11HKxcv8
        XrQBAoGBAMKBi1QatNIbVCSFnzdmsNFFVKrz7DmieyaV4ls43nOYdX5R6H8qpWIv
        WPLVLD4SbRx3n3Q7Vtl91Op7FUMNv12og4GWtAc6l7snJxJxi0g9WbiBtn1wAPEJ
        rmFQio4dhbTyJNt4G/pX4i5nk72fLZNkcOdRFImG+oWB+xXagXHB
        -----END RSA PRIVATE KEY-----
    masterprovisioning:
      dockerImageDefinitionConfiguration:
        images:
        - imageTag: "cloudbees/cloudbees-core-mm:2.387.2.4"
          name: "CloudBees CI - Managed Controller - 2.387.2.4"
      kubernetes:
        clusterEndpoints:
        - id: "default"
          ingressClass: "nginx"
          jenkinsUrl: "http://cjoc.cjoc.svc.cluster.local/cjoc/"
          name: "kubernetes"
        cpus: "1.0"
        disk: 50
        globalJavaOptions: "-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=cloudbees/cloudbees-core-agent:2.387.2.4\
          \ -Dcom.cloudbees.jenkins.plugins.kube.ServiceAccountFilter.defaultServiceAccount=jenkins-agents\
          \ -Dcom.cloudbees.networking.useSubdomain=false -Dcom.cloudbees.networking.protocol=\"\
          https\" -Dcom.cloudbees.networking.hostname=\"cjoc.apps.ocp4.example.com\" -Dcom.cloudbees.networking.port=443\
          \ -Dcom.cloudbees.networking.operationsCenterName=\"cjoc\""
        javaOptions: "-XshowSettings:vm -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+DisableExplicitGC\
          \ -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0"
        livenessInitialDelaySeconds: 300
        livenessPeriodSeconds: 10
        livenessTimeoutSeconds: 10
        memory: 3072
        readinessFailureThreshold: 100
        readinessInitialDelaySeconds: 30
        readinessTimeoutSeconds: 5
        terminationGracePeriodSeconds: 1200
    support:
      automatedBundleConfiguration:
        componentIds:
        - "CloudBeesAssuranceSupport"
        - "CloudBeesCasCBundlesSupport"
        - "CloudBeesCasCUpdateLogBundlesSupport"
        - "AgentsConfigFile"
        - "ConfigFileComponent"
        - "OtherConfigFilesComponent"
        - "AboutBrowser"
        - "AboutJenkins"
        - "AboutUser"
        - "AdministrativeMonitors"
        - "AgentProtocols"
        - "BuildQueue"
        - "CustomLogs"
        - "DumpExportTable"
        - "EnvironmentVariables"
        - "FileDescriptorLimit"
        - "GCLogs"
        - "HeapUsageHistogram"
        - "ItemsContent"
        - "AgentsJVMProcessSystemMetricsContents"
        - "MasterJVMProcessSystemMetricsContents"
        - "JenkinsLogs"
        - "LoadStats"
        - "LoggerManager"
        - "Metrics"
        - "NetworkInterfaces"
        - "NodeMonitors"
        - "OtherLogs"
        - "ReverseProxy"
        - "RootCAs"
        - "RunningBuilds"
        - "SlaveCommandStatistics"
        - "SlaveLaunchLogs"
        - "SlaveLogs"
        - "AgentsSystemConfiguration"
        - "MasterSystemConfiguration"
        - "SystemProperties"
        - "TaskLogs"
        - "ThreadDumps"
        - "UpdateCenter"
        - "UserCount"
        - "ComponentImpl"
        - "SlowRequestComponent"
        - "HighLoadComponent"
        - "DeadlockRequestComponent"
        - "KubernetesMasterLogs"
        - "KubernetesMasterManifests"
        - "ConnectedMasterSupportComponent"
        enabled: true
        period: 1
    globalCredentialsConfiguration:
      configuration:
        providerFilter: "none"
        typeFilter: "none"
    security:
      anonymizeSupportBundle:
        enabled: false
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      gitHostKeyVerificationConfiguration:
        sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
      sSHD:
        port: -1
      securitySettingsEnforcement:
        global:
          realmAndAuthorization:
            canCustomMapping: false
            canOverride: false
            defaultMappingFactory: "restrictedEquivalentRAMF"
    unclassified:
      alerter:
        recipientList:
        - email:
            emailAddresses: "alerts@test.com"
            subjectPrefix: "[Jenkins Alert]"
      buildDiscarders:
        configuredBuildDiscarders:
        - "jobBuildDiscarder"
      bundleStorageService:
        activated: false
        bundles:
        - name: "4f3c73ce-e637-4288-95cf-4922ab1178fd"
          retriever: "localFolderRetriever"
        pollingPeriod: 120
        purgeOnDeactivation: false
      experimentalPlugins:
        enabled: false
      fingerprints:
        fingerprintCleanupDisabled: false
        storage: "file"
      location:
        adminAddress: "address not configured yet <nobody@nowhere>"
        url: "https://cjoc.apps.ocp4.example.com/cjoc/"
      mailer:
        charset: "UTF-8"
        smtpHost: "smtp.test.com"
        useSsl: false
        useTls: false
      operationsCenterSharedConfiguration:
        enabled: false
      pollSCM:
        pollingThreadCount: 10
      usageStatisticsCloudBees:
        disabledJenkinsUsageStatistics: true
        usageStatisticsCollected: true
    tool:
      cloudbeesPluginUsageAnalyzer:
        enabled: true
      git:
        installations:
        - home: "git"
          name: "Default"
      mavenGlobalConfig:
        globalSettingsProvider: "standard"
        settingsProvider: "standard"
  plugins.yaml: |
    plugins:
    - id: ace-editor
    - id: antisamy-markup-formatter
    - id: apache-httpcomponents-client-4-api
    - id: authentication-tokens
    - id: aws-credentials
    - id: aws-java-sdk-ec2
    - id: aws-java-sdk-elasticbeanstalk
    - id: aws-java-sdk-minimal
    - id: blueocean-commons
    - id: blueocean-rest
    - id: bluesteel-cjoc
    - id: bouncycastle-api
    - id: caffeine-api
    - id: cloudbees-administrative-monitors
    - id: cloudbees-analytics
    - id: cloudbees-assurance
    - id: cloudbees-blueocean-default-theme
    - id: cloudbees-casc-api
    - id: cloudbees-casc-client
    - id: cloudbees-casc-items-api
    - id: cloudbees-casc-items-commons
    - id: cloudbees-casc-server
    - id: cloudbees-folder
    - id: cloudbees-folders-plus
    - id: cloudbees-jenkins-advisor
    - id: cloudbees-license
    - id: cloudbees-monitoring
    - id: cloudbees-platform-common
    - id: cloudbees-platform-data
    - id: cloudbees-plugin-usage
    - id: cloudbees-ssh-slaves
    - id: cloudbees-support
    - id: cloudbees-uc-data-api
    - id: cloudbees-unified-ui
    - id: cloudbees-update-center-plugin
    - id: command-launcher
    - id: commons-lang3-api
    - id: commons-text-api
    - id: configuration-as-code
    - id: credentials
    - id: credentials-binding
    - id: display-url-api
    - id: docker-commons
    - id: durable-task
    - id: git-client
    - id: handy-uri-templates-2-api
    - id: infradna-backup
    - id: instance-identity
    - id: ionicons-api
    - id: jackson2-api
    - id: jakarta-activation-api
    - id: jakarta-mail-api
    - id: javax-activation-api
    - id: javax-mail-api
    - id: jaxb
    - id: jdk-tool
    - id: jjwt-api
    - id: jquery3-api
    - id: kube-agent-management
    - id: kubernetes
    - id: kubernetes-client-api
    - id: kubernetes-credentials
    - id: ldap
    - id: mailer
    - id: mapdb-api
    - id: master-provisioning-core
    - id: master-provisioning-kubernetes
    - id: metrics
    - id: mina-sshd-api-common
    - id: mina-sshd-api-core
    - id: mina-sshd-api-scp
    - id: mina-sshd-api-sftp
    - id: nectar-license
    - id: nectar-rbac
    - id: node-iterator-api
    - id: notification-api
    - id: oauth-credentials
    - id: okhttp-api
    - id: operations-center-agent
    - id: operations-center-clusterops
    - id: operations-center-context
    - id: operations-center-elasticsearch-provider
    - id: operations-center-jnlp-controller
    - id: operations-center-kubernetes-cloud
    - id: operations-center-license
    - id: operations-center-monitoring
    - id: operations-center-notification
    - id: operations-center-rbac
    - id: operations-center-server
    - id: operations-center-sso
    - id: operations-center-updatecenter
    - id: plain-credentials
    - id: pubsub-light
    - id: scm-api
    - id: script-security
    - id: snakeyaml-api
    - id: sse-gateway
    - id: ssh-credentials
    - id: sshd
    - id: structs
    - id: support-core
    - id: token-macro
    - id: trilead-api
    - id: unique-id
    - id: user-activity-monitoring
    - id: variant
    - id: workflow-api
    - id: workflow-durable-task-step
    - id: workflow-step-api
    - id: workflow-support
kind: ConfigMap
metadata:
  name: oc-casc-bundle
  namespace: cjoc-casc
